service: rainalert

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  rainalert:
    handler: bin/rainalert
    events:
      - http:
          path: rainalert
          method: get
      - schedule: rate(1 hour)
